In [1]:
import numpy as np
import pandas as pd

In [2]:
# 17. chinv
# 季度频率。存货变动除以总资产。

df1 = pd.read_csv('季_资产负债表.csv', usecols=['证券代码', '会计期间', '存货净额', '资产总计'], low_memory=False)
df1['存货比'] = df1['存货净额']/df1['资产总计'].replace(0, np.nan)
df1['chinv'] = df1['存货比'] - df1.groupby('证券代码').shift(1)['存货比']
df2 = df1[['证券代码', '会计期间', 'chinv']]
df2.to_csv('季_17.csv', index=False, encoding='utf-8-sig')
df2

          证券代码        会计期间  chinv
0            1  2000-03-31    NaN
1            1  2000-06-30    NaN
2            1  2000-09-30    NaN
3            1  2000-12-31    NaN
4            1  2001-03-31    NaN
...        ...         ...    ...
571126  920118  2023-09-30    NaN
571127  920118  2023-12-31    NaN
571128  920118  2024-03-31    NaN
571129  920118  2024-06-30    NaN
571130  920118  2024-09-30    NaN

[571131 rows x 3 columns]