In [1]:
import numpy as np
import pandas as pd
from utils.diff import diff

In [2]:
# 76.  salerev
# 季度频率。季度销售额除以应收账款。

df1 = pd.read_csv('季_资产负债表.csv', usecols=['证券代码', '会计期间', '应收账款净额'])
df1['证券代码'] = pd.to_numeric(df1['证券代码'], errors='coerce').fillna(0).astype(int)
df2 = pd.read_csv('季_利润表.csv', usecols=['证券代码', '会计期间', '营业收入'])
df2['证券代码'] = pd.to_numeric(df2['证券代码'], errors='coerce').fillna(0).astype(int)
df3 = pd.merge(df1, df2, on=['证券代码', '会计期间'], how='left')
df3 = diff(df3, col=['营业收入'])
df3['salerev'] = df3['营业收入']/df3['应收账款净额'].replace(0, np.nan)
df4 = df3[['证券代码', '会计期间', 'salerev']]
df4.to_csv('季_76.csv', index=False, encoding='utf-8-sig')
df4

          证券代码        会计期间  salerev
0            1  2000-03-31      NaN
1            1  2000-06-30      NaN
2            1  2000-09-30      NaN
3            1  2000-12-31      NaN
4            1  2001-03-31      NaN
...        ...         ...      ...
571126  920118  2023-09-30      NaN
571127  920118  2023-12-31      NaN
571128  920118  2024-03-31      NaN
571129  920118  2024-06-30      NaN
571130  920118  2024-09-30      NaN

[571131 rows x 3 columns]