In [1]:
import numpy as np
import pandas as pd

In [2]:
# 37. invest
# 年频率。固定资产年度变动与存货年度变动除以滞后总资产的总和。

df1 = pd.read_csv('季_资产负债表.csv', usecols=['证券代码', '会计期间', '固定资产净额', '存货净额', '资产总计'])
df1['证券代码'] = pd.to_numeric(df1['证券代码'], errors='coerce').fillna(0).astype(int)

df1['年'] = df1['会计期间'].apply(lambda x: True if x[5:7] == '12' else False)
df1 = df1[df1['年']].reset_index().drop(columns=['index'])
df1['invest'] = (df1['固定资产净额'] - df1.groupby('证券代码').shift(1)['固定资产净额'] + df1['存货净额'] - df1.groupby('证券代码').shift(1)['存货净额'])/df1.groupby('证券代码').shift(1)['资产总计'].replace(0, np.nan)
df2 = df1[['证券代码', '会计期间', 'invest']]
df2.to_csv('年_37.csv', index=False, encoding='utf-8-sig')
df2

          证券代码        会计期间  invest
0            1  2000-12-31     NaN
1            1  2001-12-31     NaN
2            1  2002-12-31     NaN
3            1  2003-12-31     NaN
4            1  2004-12-31     NaN
...        ...         ...     ...
138451  920118  2019-12-31     NaN
138452  920118  2020-12-31     NaN
138453  920118  2021-12-31     NaN
138454  920118  2022-12-31     NaN
138455  920118  2023-12-31     NaN

[138456 rows x 3 columns]